models:
  - id: "deepclaude"
    object: "model"
    created: 1740268800
    owned_by: "deepclaude"
    permission:
      - id: "modelperm-deepclaude"
        object: "model_permission"
        created: 1740268800
        allow_create_engine: false
        allow_sampling: true
        allow_logprobs: true
        allow_search_indices: false
        allow_view: true
        allow_fine_tuning: false
        organization: "*"
        group: null
        is_blocking: false
    root: "deepclaude"
    parent: null

  - id: "deepgemini"
    object: "model"
    created: 1740268800
    owned_by: "deepclaude"
    permission:
      - id: "modelperm-deepgemini"
        object: "model_permission"
        created: 1740268800
        allow_create_engine: false
        allow_sampling: true
        allow_logprobs: true
        allow_search_indices: false
        allow_view: true
        allow_fine_tuning: false
        organization: "*"
        group: null
        is_blocking: false
    root: "deepgemini"
    parent: null
